<template>
  <div class="loadingio-spinner-ripple-su4pmc0qfnd">
    <div class="ldio-xuwxdbpe6z8">
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ClickRipple',
  data() {
    return {}
  }
}
</script>

<style lang="stylus" scoped>
@keyframes ldio-xuwxdbpe6z8 {
  0% {
    top: 21px;
    left: 21px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 0;
    left: 0;
    width: 42px;
    height: 42px;
    opacity: 0;
  }
}

.ldio-xuwxdbpe6z8 div {
  // position: absolute;
  // border-width: 4px;
  // border-style: solid;
  // opacity: 1;
  // border-radius: 50%;
  // animation: ldio-xuwxdbpe6z8 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}

// .ldio-xuwxdbpe6z8 div:nth-child(1) {
//   border-color: #e90c59;
// }

// .ldio-xuwxdbpe6z8 div:nth-child(2) {
//   border-color: #46dff0;
//   animation-delay: -0.5s;
// }

.loadingio-spinner-ripple-su4pmc0qfnd {
  width: 50px;
  height: 50px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-xuwxdbpe6z8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
  div {
    position: absolute;
    border-width: 4px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: ldio-xuwxdbpe6z8 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
    box-sizing: content-box;
    &:nth-child(1) {
      border-color: #e90c59;
    }
    &:nth-child(2) {
      border-color: #46dff0;
      animation-delay: -0.5s;
    }
  }
}
/* generated by https://loading.io/ */
</style>
